name: Tests

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 5
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12


      - name: Install dependencies
        run: |
          py -m pip install --upgrade pip
          py -3 -m pip install robotpy==2024.1.1.3
          pip install coverage
          py -3 -m robotpy sync --user


      - name:
        run: |
          py -3 -m robotpy test
